apiVersion: v1
kind: ConfigMap
metadata:
  name: wargacare-config
  namespace: wargacare
data:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres-service:5432/wargacare"
  SPRING_DATASOURCE_USERNAME: "postgres"
  SPRING_JPA_HIBERNATE_DDL_AUTO: "validate"
