CREATE TABLE IF NOT EXISTS reports (
    id            BIGINT          GENERATED BY DEFAULT AS IDENTITY,
    title         VARCHAR(200)    NOT NULL,
    description   TEXT            NOT NULL,
    category      VARCHAR(30)     NOT NULL,
    status        VARCHAR(20)     NOT NULL DEFAULT 'PENDING',
    location      VARCHAR(255)    NULL,
    rt            VARCHAR(10)     NULL,
    rw            VARCHAR(10)     NULL,
    admin_notes   TEXT            NULL,
    reporter_id   BIGINT          NOT NULL,
    created_at    TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT fk_reports_reporter FOREIGN KEY (reporter_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_reports_category ON reports (category);
CREATE INDEX IF NOT EXISTS idx_reports_status ON reports (status);
CREATE INDEX IF NOT EXISTS idx_reports_reporter ON reports (reporter_id);
CREATE INDEX IF NOT EXISTS idx_reports_rt_rw ON reports (rt, rw);
