CREATE TABLE IF NOT EXISTS announcements (
    id          BIGINT          GENERATED BY DEFAULT AS IDENTITY,
    title       VARCHAR(200)    NOT NULL,
    content     TEXT            NOT NULL,
    is_pinned   BOOLEAN         NOT NULL DEFAULT FALSE,
    author_id   BIGINT          NOT NULL,
    created_at  TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT fk_announcements_author FOREIGN KEY (author_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_announcements_pinned ON announcements (is_pinned);
CREATE INDEX IF NOT EXISTS idx_announcements_author ON announcements (author_id);

CREATE TABLE IF NOT EXISTS events (
    id              BIGINT          GENERATED BY DEFAULT AS IDENTITY,
    title           VARCHAR(200)    NOT NULL,
    description     TEXT            NOT NULL,
    event_date      TIMESTAMP       NOT NULL,
    location        VARCHAR(255)    NULL,
    organizer_id    BIGINT          NOT NULL,
    created_at      TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT fk_events_organizer FOREIGN KEY (organizer_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_events_date ON events (event_date);
CREATE INDEX IF NOT EXISTS idx_events_organizer ON events (organizer_id);
