CREATE TABLE IF NOT EXISTS kas_transactions (
    id            BIGINT          GENERATED BY DEFAULT AS IDENTITY,
    rt            VARCHAR(10)     NOT NULL,
    type          VARCHAR(20)     NOT NULL,
    title         VARCHAR(255)    NOT NULL,
    amount        NUMERIC(15, 2)  NOT NULL DEFAULT 0.00,
    category      VARCHAR(100)    NOT NULL,
    date          DATE            NOT NULL,
    recorded_by   VARCHAR(150)    NULL,
    notes         TEXT            NULL,
    proof_url     VARCHAR(500)    NULL,
    created_at    TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_kas_rt ON kas_transactions (rt);
CREATE INDEX IF NOT EXISTS idx_kas_type ON kas_transactions (type);
CREATE INDEX IF NOT EXISTS idx_kas_category ON kas_transactions (category);
CREATE INDEX IF NOT EXISTS idx_kas_date ON kas_transactions (date);

CREATE TABLE IF NOT EXISTS iuran_warga (
    id             BIGINT          GENERATED BY DEFAULT AS IDENTITY,
    user_id        BIGINT          NULL,
    warga_name     VARCHAR(100)    NOT NULL,
    block_address  VARCHAR(100)    NULL,
    rt             VARCHAR(10)     NOT NULL,
    period_month   VARCHAR(10)     NOT NULL,
    amount         NUMERIC(15, 2)  NOT NULL DEFAULT 50000.00,
    is_paid        BOOLEAN         NOT NULL DEFAULT FALSE,
    paid_date      DATE            NULL,
    payment_method VARCHAR(50)     NULL,
    recorded_by    VARCHAR(150)    NULL,
    created_at    TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT fk_iuran_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_iuran_rt ON iuran_warga (rt);
CREATE INDEX IF NOT EXISTS idx_iuran_period ON iuran_warga (period_month);
