CREATE TABLE IF NOT EXISTS warga_master (
    id            BIGINT          GENERATED BY DEFAULT AS IDENTITY,
    warga_name    VARCHAR(100)    NOT NULL,
    block_address VARCHAR(100)    NULL,
    rt            VARCHAR(10)     NOT NULL,
    category      VARCHAR(20)     NOT NULL DEFAULT 'PEKERJA',
    created_at    TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_warga_master_rt ON warga_master (rt);
CREATE INDEX IF NOT EXISTS idx_warga_master_name ON warga_master (warga_name);

ALTER TABLE iuran_warga ADD COLUMN IF NOT EXISTS period_week VARCHAR(10) NULL;
ALTER TABLE iuran_warga ADD COLUMN IF NOT EXISTS warga_master_id BIGINT NULL;

CREATE INDEX IF NOT EXISTS idx_iuran_period_week ON iuran_warga (period_week);
